Sprint 12 homework
pavlovAndrei/java-filmorate pull request #4
Opened 2022-11-10 15:29 UTC by pavlovAndrei

2022-11-10 19:10 UTC, eugene-lenkevich requested changes
Привет, Андрей, спасибо за PR

В целом все отлично, запросы в БД, смотрю, используешь достаточно сложные :)
Есть совсем небольшие пометки и вопросы, посмотри комментарии ниже, пожалуйста

2022-11-10 19:10 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        final String sqlQuery = "SELECT * FROM FILMS JOIN RATES ON FILMS.RATE_ID = RATES.ID WHERE FILMS.ID = ?";
JOIN RATES 

Кстати, а если рейтингов не будет отработает ли этот запрос корректно, может лучше LEFT JOIN RATES, тогда мы получим и те фильмы, у которых нет рейтингов?

2022-11-10 19:10 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/mapper/UserMapper.java
> +public class UserMapper implements RowMapper<User> {
Эти мапперы можно сделать спринговыми бинами, достаточно добавить @Component сверху класса и далее инжектить как и остальные бины, а инжектстить кстати можно вот так, указывая интерйейс :)

@Service
class MyService {
  private final RowMapper<User> userMapper;
...
}

Попробуй так сделать :)

2022-11-10 19:10 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        getFilmById(film.getId());
А если метод тут вызываеть с именем, например, checkIfFilmExist, добавить ли это наглядности коду?
Мы вызываем get-метод, его значение никуда не не передаем, если не заглянуть внутрь и не увидеть что там бросается исключение, то и не понять что именно тут происходиn :)

2022-11-10 19:17 UTC, pavlovAndrei commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Collection<Film> getAllFilms() {
Согласен. Поменял во всех котроллерах для единообразия

2022-11-10 19:17 UTC, pavlovAndrei commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +    private final GenreStorage genreStorage;
Добавил

2022-11-10 19:18 UTC, pavlovAndrei commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        final String sqlQuery = "SELECT * FROM FILMS JOIN RATES ON FILMS.RATE_ID = RATES.ID WHERE FILMS.ID = ?";
Хорошее замечание. Это было в условиях, но упустил момент.

2022-11-10 19:34 UTC, pavlovAndrei commented on src/main/java/ru/yandex/practicum/filmorate/mapper/UserMapper.java
> +public class UserMapper implements RowMapper<User> {
Спасибо за совет! поменял во всех классах

2022-11-10 19:38 UTC, pavlovAndrei commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        getFilmById(film.getId());
Верно. Добавио ясности

2022-11-11 04:53 UTC, eugene-lenkevich approved these changes
Привет, спасибо за доработку

Во, как по мне так код стал заметно лаконичней  :)

PS

`private final RowMapper<Genre> genreMapper;`

В принципе сюда можно было инжектить и конкретный класс маппера, ничего бы страшного не произошло, работало бы и так. Но, с архитектурной точки зрения, более правильно зависеть от интерфейсов. В таком случае можно подменить реализацию (например подгрузить конфигурацию в  которой будет другая реализация этого интерфейса) вообще без изменений в основном коде. Самый простой пример - тесты, мы можем так заменять реализации, например, сервисов, которые обращаются к внешним системам своими заглушками.
В общем то весь spring на этом принципе и работает :)

2022-11-11 05:00 UTC, merged